SET BIGAAAOPTIFLOW(AAA)                                                                                                                                                                        
/                                                                                                                                                                                              
Esbjerg                                                                                                                                                                                        
Koebenhavn                                                                                                                                                                                     
Odense                                                                                                                                                                                         
Aalborg                                                                                                                                                                                        
Aarhus                                                                                                                                                                                         
Middelfart                                                                                                              !! TVIS district heating area                                          
Fredericia                                                                                                              !! TVIS district heating area                                          
Vejle                                                                                                                   !! TVIS district heating area                                          
Kolding                                                                                                                 !! TVIS district heating area                                          
/                                                                                                                                                                                              
SET MUNAAAOPTIFLOW(AAA)                                                                                                                                                                        
/                                                                                                                                                                                              
Albertslund                                                                                                                                                                                    
Alleroed                                                                                                                                                                                       
Assens                                                                                                                                                                                         
Ballerup                                                                                                                                                                                       
Billund                                                                                                                                                                                        
Bornholm                                                                                                                                                                                       
Broendby                                                                                                                                                                                       
Broenderslev                                                                                                                                                                                   
Christiansoe                                                                                                                                                                                   
Dragoer                                                                                                                                                                                        
Egedal                                                                                                                                                                                         
Esbjerg                                                                                                                                                                                        
Fanoe                                                                                                                                                                                          
Favrskov                                                                                                                                                                                       
Faxe                                                                                                                                                                                           
Fredensborg                                                                                                                                                                                    
Fredericia                                                                                                                                                                                     
Frederiksberg                                                                                                                                                                                  
Frederikshavn                                                                                                                                                                                  
Frederikssund                                                                                                                                                                                  
Furesoe                                                                                                                                                                                        
Faaborg-Midtfyn                                                                                                                                                                                
Gentofte                                                                                                                                                                                       
Gladsaxe                                                                                                                                                                                       
Glostrup                                                                                                                                                                                       
Greve                                                                                                                                                                                          
Gribskov                                                                                                                                                                                       
Guldborgsund                                                                                                                                                                                   
Haderslev                                                                                                                                                                                      
Halsnaes                                                                                                                                                                                       
Hedensted                                                                                                                                                                                      
Helsingoer                                                                                                                                                                                     
Herlev                                                                                                                                                                                         
Herning                                                                                                                                                                                        
Hilleroed                                                                                                                                                                                      
Hjoerring                                                                                                                                                                                      
Holbaek                                                                                                                                                                                        
Holstebro                                                                                                                                                                                      
Horsens                                                                                                                                                                                        
Hvidovre                                                                                                                                                                                       
Hoeje_Taastrup                                                                                                                                                                                 
Hoersholm                                                                                                                                                                                      
Ikast-Brande                                                                                                                                                                                   
Ishoej                                                                                                                                                                                         
Jammerbugt                                                                                                                                                                                     
Kalundborg                                                                                                                                                                                     
Kerteminde                                                                                                                                                                                     
Kolding                                                                                                                                                                                        
Koebenhavn                                                                                                                                                                                     
Koege                                                                                                                                                                                          
Langeland                                                                                                                                                                                      
Lejre                                                                                                                                                                                          
Lemvig                                                                                                                                                                                         
Lolland                                                                                                                                                                                        
Lyngby-Taarbaek                                                                                                                                                                                
Laesoe                                                                                                                                                                                         
Mariagerfjord                                                                                                                                                                                  
Middelfart                                                                                                                                                                                     
Morsoe                                                                                                                                                                                         
Norddjurs                                                                                                                                                                                      
Nordfyns                                                                                                                                                                                       
Nyborg                                                                                                                                                                                         
Naestved                                                                                                                                                                                       
Odder                                                                                                                                                                                          
Odense                                                                                                                                                                                         
Odsherred                                                                                                                                                                                      
Randers                                                                                                                                                                                        
Rebild                                                                                                                                                                                         
Ringkoebing-Skjern                                                                                                                                                                             
Ringsted                                                                                                                                                                                       
Roskilde                                                                                                                                                                                       
Rudersdal                                                                                                                                                                                      
Roedovre                                                                                                                                                                                       
Samsoe                                                                                                                                                                                         
Silkeborg                                                                                                                                                                                      
Skanderborg                                                                                                                                                                                    
Skive                                                                                                                                                                                          
Slagelse                                                                                                                                                                                       
Solroed                                                                                                                                                                                        
Soroe                                                                                                                                                                                          
Stevns                                                                                                                                                                                         
Struer                                                                                                                                                                                         
Svendborg                                                                                                                                                                                      
Syddjurs                                                                                                                                                                                       
Soenderborg                                                                                                                                                                                    
Thisted                                                                                                                                                                                        
Toender                                                                                                                                                                                        
Taarnby                                                                                                                                                                                        
Vallensbaek                                                                                                                                                                                    
Varde                                                                                                                                                                                          
Vejen                                                                                                                                                                                          
Vejle                                                                                                                                                                                          
Vesthimmerlands                                                                                                                                                                                
Viborg                                                                                                                                                                                         
Vordingborg                                                                                                                                                                                    
Aeroe                                                                                                                                                                                          
Aabenraa                                                                                                                                                                                       
Aalborg                                                                                                                                                                                        
Aarhus                                                                                                                                                                                         
                                                                                                                                                                                               
/;                                                                                                                                                                                             
                                                                                                                                                                                               
SET APROCKAPNEW(YYY,AAA,PROC)     'Areas for possible location of new Proc or capacity expansion of existing Proc'                                                                             
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
/                                                                                                                                                                                              
                                                                                                                                                                                               
***CO2                                                                                                                                                                                         
2020                                                                                                                    .                             Aarhus .    CO2_DAC_20                   
2025                                                                                                                    .                             Aarhus .    CO2_DAC_25                   
2030                                                                                                                    .                             Aarhus .    CO2_DAC_30                   
2035                                                                                                                    .                             Aarhus .    CO2_DAC_35                   
2040                                                                                                                    .                             Aarhus .    CO2_DAC_40                   
2045                                                                                                                    .                             Aarhus .    CO2_DAC_45                   
2050                                                                                                                    .                             Aarhus .    CO2_DAC_50                   
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
*                                                                                                                                                                                              
2020                                                                                                                    .                             Aarhus .    CO2_STO                      
2025                                                                                                                    .                             Aarhus .    CO2_STO                      
2030                                                                                                                    .                             Aarhus .    CO2_STO                      
2035                                                                                                                    .                             Aarhus .    CO2_STO                      
2040                                                                                                                    .                             Aarhus .    CO2_STO                      
2045                                                                                                                    .                             Aarhus .    CO2_STO                      
2050                                                                                                                    .                             Aarhus .    CO2_STO                      
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
* OBS FF                                                                                                                                                                                       
$ifi not %baloptCCS%==yes $goto NO_CCS                                                                                                                                                         
2020                                                                                                                    .                             Aarhus .    CO2_Seq_20                   
2025                                                                                                                    .                             Aarhus .    CO2_Seq_25                   
2030                                                                                                                    .                             Aarhus .    CO2_Seq_30                   
2035                                                                                                                    .                             Aarhus .    CO2_Seq_35                   
2040                                                                                                                    .                             Aarhus .    CO2_Seq_40                   
2045                                                                                                                    .                             Aarhus .    CO2_Seq_45                   
2050                                                                                                                    .                             Aarhus .    CO2_Seq_50                   
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
$label NO_CCS                                                                                                                                                                                  
                                                                                                                                                                                               
*OBS FF                                                                                                                                                                                        
$ifi not %baloptgasbridge%==yes $goto NO_BIOGAS                                                                                                                                                
2020                                                                                                                    .                             Aarhus .    Digestion_Tank_20            
2025                                                                                                                    .                             Aarhus .    Digestion_Tank_25            
2030                                                                                                                    .                             Aarhus .    Digestion_Tank_30            
2035                                                                                                                    .                             Aarhus .    Digestion_Tank_35            
2040                                                                                                                    .                             Aarhus .    Digestion_Tank_40            
2045                                                                                                                    .                             Aarhus .    Digestion_Tank_45            
2050                                                                                                                    .                             Aarhus .    Digestion_Tank_50            
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    Methanation_20               
2025                                                                                                                    .                             Aarhus .    Methanation_25               
2030                                                                                                                    .                             Aarhus .    Methanation_30               
2035                                                                                                                    .                             Aarhus .    Methanation_35               
2040                                                                                                                    .                             Aarhus .    Methanation_40               
2045                                                                                                                    .                             Aarhus .    Methanation_45               
2050                                                                                                                    .                             Aarhus .    Methanation_50               
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    Biogas_Upgrading_20          
2025                                                                                                                    .                             Aarhus .    Biogas_Upgrading_25          
2030                                                                                                                    .                             Aarhus .    Biogas_Upgrading_30          
2035                                                                                                                    .                             Aarhus .    Biogas_Upgrading_35          
2040                                                                                                                    .                             Aarhus .    Biogas_Upgrading_40          
2045                                                                                                                    .                             Aarhus .    Biogas_Upgrading_45          
2050                                                                                                                    .                             Aarhus .    Biogas_Upgrading_50          
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
$label NO_BIOGAS                                                                                                                                                                               
                                                                                                                                                                                               
***TG                                                                                                                                                                                          
2020                                                                                                                    .                             Aarhus .    TG_20                        
2025                                                                                                                    .                             Aarhus .    TG_25                        
2030                                                                                                                    .                             Aarhus .    TG_30                        
2035                                                                                                                    .                             Aarhus .    TG_35                        
2040                                                                                                                    .                             Aarhus .    TG_40                        
2045                                                                                                                    .                             Aarhus .    TG_45                        
2050                                                                                                                    .                             Aarhus .    TG_50                        
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
***Methanol                                                                                                                                                                                    
2020                                                                                                                    .                             Aarhus .    Methanol_synthesis_TG_20     
2025                                                                                                                    .                             Aarhus .    Methanol_synthesis_TG_25     
2030                                                                                                                    .                             Aarhus .    Methanol_synthesis_TG_30     
2035                                                                                                                    .                             Aarhus .    Methanol_synthesis_TG_35     
2040                                                                                                                    .                             Aarhus .    Methanol_synthesis_TG_40     
2045                                                                                                                    .                             Aarhus .    Methanol_synthesis_TG_45     
2050                                                                                                                    .                             Aarhus .    Methanol_synthesis_TG_50     
*                                                                                                                                                                                              
2020                                                                                                                    .                             Aarhus .    EMethanol_synthesis_20       
2025                                                                                                                    .                             Aarhus .    EMethanol_synthesis_25       
2030                                                                                                                    .                             Aarhus .    EMethanol_synthesis_30       
2035                                                                                                                    .                             Aarhus .    EMethanol_synthesis_35       
2040                                                                                                                    .                             Aarhus .    EMethanol_synthesis_40       
2045                                                                                                                    .                             Aarhus .    EMethanol_synthesis_45       
2050                                                                                                                    .                             Aarhus .    EMethanol_synthesis_50       
*                                                                                                                                                                                              
2020                                                                                                                    .                             Aarhus .    EMethanol_Upgrade_20         
2025                                                                                                                    .                             Aarhus .    EMethanol_Upgrade_25         
2030                                                                                                                    .                             Aarhus .    EMethanol_Upgrade_30         
2035                                                                                                                    .                             Aarhus .    EMethanol_Upgrade_35         
2040                                                                                                                    .                             Aarhus .    EMethanol_Upgrade_40         
2045                                                                                                                    .                             Aarhus .    EMethanol_Upgrade_45         
2050                                                                                                                    .                             Aarhus .    EMethanol_Upgrade_50         
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
***Ammonia                                                                                                                                                                                     
2020                                                                                                                    .                             Aarhus .    Ammonia_Synthesis_20         
2025                                                                                                                    .                             Aarhus .    Ammonia_Synthesis_25         
2030                                                                                                                    .                             Aarhus .    Ammonia_Synthesis_30         
2035                                                                                                                    .                             Aarhus .    Ammonia_Synthesis_35         
2040                                                                                                                    .                             Aarhus .    Ammonia_Synthesis_40         
2045                                                                                                                    .                             Aarhus .    Ammonia_Synthesis_45         
2050                                                                                                                    .                             Aarhus .    Ammonia_Synthesis_50         
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
***Jet and oil products                                                                                                                                                                        
2020                                                                                                                    .                             Aarhus .    BioJet_20                    
2025                                                                                                                    .                             Aarhus .    BioJet_25                    
2030                                                                                                                    .                             Aarhus .    BioJet_30                    
2035                                                                                                                    .                             Aarhus .    BioJet_35                    
2040                                                                                                                    .                             Aarhus .    BioJet_40                    
2045                                                                                                                    .                             Aarhus .    BioJet_45                    
2050                                                                                                                    .                             Aarhus .    BioJet_50                    
*                                                                                                                                                                                              
2020                                                                                                                    .                             Aarhus .    BioJet_H2_20                 
2025                                                                                                                    .                             Aarhus .    BioJet_H2_25                 
2030                                                                                                                    .                             Aarhus .    BioJet_H2_30                 
2035                                                                                                                    .                             Aarhus .    BioJet_H2_35                 
2040                                                                                                                    .                             Aarhus .    BioJet_H2_40                 
2045                                                                                                                    .                             Aarhus .    BioJet_H2_45                 
2050                                                                                                                    .                             Aarhus .    BioJet_H2_50                 
*                                                                                                                                                                                              
2020                                                                                                                    .                             Aarhus .    E_FT_20                      
2025                                                                                                                    .                             Aarhus .    E_FT_25                      
2030                                                                                                                    .                             Aarhus .    E_FT_30                      
2035                                                                                                                    .                             Aarhus .    E_FT_35                      
2040                                                                                                                    .                             Aarhus .    E_FT_40                      
2045                                                                                                                    .                             Aarhus .    E_FT_45                      
2050                                                                                                                    .                             Aarhus .    E_FT_50                      
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
*Rossella LUOptiflow                                                                                                                                                                           
*$ifi not %baloptLU%==yes $goto NO_LU                                                                                                                                                          
*Forest                                                                                                                                                                                        
2020                                                                                                                    .                             Aarhus .    Untouched_Forest             
2025                                                                                                                    .                             Aarhus .    Untouched_Forest             
2030                                                                                                                    .                             Aarhus .    Untouched_Forest             
2035                                                                                                                    .                             Aarhus .    Untouched_Forest             
2040                                                                                                                    .                             Aarhus .    Untouched_Forest             
2045                                                                                                                    .                             Aarhus .    Untouched_Forest             
2050                                                                                                                    .                             Aarhus .    Untouched_Forest             
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    Wood_Production              
2025                                                                                                                    .                             Aarhus .    Wood_Production              
2030                                                                                                                    .                             Aarhus .    Wood_Production              
2035                                                                                                                    .                             Aarhus .    Wood_Production              
2040                                                                                                                    .                             Aarhus .    Wood_Production              
2045                                                                                                                    .                             Aarhus .    Wood_Production              
2050                                                                                                                    .                             Aarhus .    Wood_Production              
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    C_Rich_Soils_Extraction      
2025                                                                                                                    .                             Aarhus .    C_Rich_Soils_Extraction      
2030                                                                                                                    .                             Aarhus .    C_Rich_Soils_Extraction      
2035                                                                                                                    .                             Aarhus .    C_Rich_Soils_Extraction      
2040                                                                                                                    .                             Aarhus .    C_Rich_Soils_Extraction      
2045                                                                                                                    .                             Aarhus .    C_Rich_Soils_Extraction      
2050                                                                                                                    .                             Aarhus .    C_Rich_Soils_Extraction      
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    Wheat_Agriculture            
2025                                                                                                                    .                             Aarhus .    Wheat_Agriculture            
2030                                                                                                                    .                             Aarhus .    Wheat_Agriculture            
2035                                                                                                                    .                             Aarhus .    Wheat_Agriculture            
2040                                                                                                                    .                             Aarhus .    Wheat_Agriculture            
2045                                                                                                                    .                             Aarhus .    Wheat_Agriculture            
2050                                                                                                                    .                             Aarhus .    Wheat_Agriculture            
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    Barley_Agriculture           
2025                                                                                                                    .                             Aarhus .    Barley_Agriculture           
2030                                                                                                                    .                             Aarhus .    Barley_Agriculture           
2035                                                                                                                    .                             Aarhus .    Barley_Agriculture           
2040                                                                                                                    .                             Aarhus .    Barley_Agriculture           
2045                                                                                                                    .                             Aarhus .    Barley_Agriculture           
2050                                                                                                                    .                             Aarhus .    Barley_Agriculture           
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    Rye_Agriculture              
2025                                                                                                                    .                             Aarhus .    Rye_Agriculture              
2030                                                                                                                    .                             Aarhus .    Rye_Agriculture              
2035                                                                                                                    .                             Aarhus .    Rye_Agriculture              
2040                                                                                                                    .                             Aarhus .    Rye_Agriculture              
2045                                                                                                                    .                             Aarhus .    Rye_Agriculture              
2050                                                                                                                    .                             Aarhus .    Rye_Agriculture              
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    Oat_Agriculture              
2025                                                                                                                    .                             Aarhus .    Oat_Agriculture              
2030                                                                                                                    .                             Aarhus .    Oat_Agriculture              
2035                                                                                                                    .                             Aarhus .    Oat_Agriculture              
2040                                                                                                                    .                             Aarhus .    Oat_Agriculture              
2045                                                                                                                    .                             Aarhus .    Oat_Agriculture              
2050                                                                                                                    .                             Aarhus .    Oat_Agriculture              
                                                                                                                                                                                               
2020                                                                                                                    .                             Aarhus .    New_Productive_Forest        
2025                                                                                                                    .                             Aarhus .    New_Productive_Forest        
2030                                                                                                                    .                             Aarhus .    New_Productive_Forest        
2035                                                                                                                    .                             Aarhus .    New_Productive_Forest        
2040                                                                                                                    .                             Aarhus .    New_Productive_Forest        
2045                                                                                                                    .                             Aarhus .    New_Productive_Forest        
2050                                                                                                                    .                             Aarhus .    New_Productive_Forest        
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
                                                                                                                                                                                               
*$label NO_LU                                                                                                                                                                                  
                                                                                                                                                                                               
/                                                                                                                                                                                              
;                                                                                                                                                                                              
                                                                                                                                                                                               
APROCKAPNEW(Y,AAA,'CO2_DAC_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_20');                                                                                                      
 APROCKAPNEW(Y,AAA,'CO2_DAC_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_25');                                                                                                     
APROCKAPNEW(Y,AAA,'CO2_DAC_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_30');                                                                                                      
APROCKAPNEW(Y,AAA,'CO2_DAC_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_35');                                                                                                      
APROCKAPNEW(Y,AAA,'CO2_DAC_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_40');                                                                                                      
APROCKAPNEW(Y,AAA,'CO2_DAC_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_45');                                                                                                      
APROCKAPNEW(Y,AAA,'CO2_DAC_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_DAC_50');                                                                                                      
                                                                                                                                                                                               
APROCKAPNEW(Y,AAA,'CO2_STO')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_STO');                                                                                                            
$ifi not %baloptCCS%==yes $goto NO_CCS                                                                                                                                                         
APROCKAPNEW(Y,AAA,'CO2_Seq_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_Seq_20');                                                                                                      
 APROCKAPNEW(Y,AAA,'CO2_Seq_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_Seq_25');                                                                                                     
 APROCKAPNEW(Y,AAA,'CO2_Seq_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_Seq_30');                                                                                                     
APROCKAPNEW(Y,AAA,'CO2_Seq_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_Seq_35');                                                                                                      
APROCKAPNEW(Y,AAA,'CO2_Seq_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_Seq_40');                                                                                                      
APROCKAPNEW(Y,AAA,'CO2_Seq_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_Seq_45');                                                                                                      
 APROCKAPNEW(Y,AAA,'CO2_Seq_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','CO2_Seq_50');                                                                                                     
$label NO_CCS                                                                                                                                                                                  
$ifi not %baloptgasbridge%==yes $goto NO_BIOGAS                                                                                                                                                
APROCKAPNEW(Y,AAA,'Digestion_Tank_20')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_20');                                                                                        
APROCKAPNEW(Y,AAA,'Digestion_Tank_25')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_25');                                                                                        
APROCKAPNEW(Y,AAA,'Digestion_Tank_30')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_30');                                                                                        
APROCKAPNEW(Y,AAA,'Digestion_Tank_35')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_35');                                                                                        
APROCKAPNEW(Y,AAA,'Digestion_Tank_40')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_40');                                                                                        
 APROCKAPNEW(Y,AAA,'Digestion_Tank_45')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_45');                                                                                       
 APROCKAPNEW(Y,AAA,'Digestion_Tank_50')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Digestion_Tank_50');                                                                                       
APROCKAPNEW(Y,AAA,'Methanation_20')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_20');                                                                                              
APROCKAPNEW(Y,AAA,'Methanation_25')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_25');                                                                                              
 APROCKAPNEW(Y,AAA,'Methanation_30')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_30');                                                                                             
 APROCKAPNEW(Y,AAA,'Methanation_35')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_35');                                                                                             
 APROCKAPNEW(Y,AAA,'Methanation_40')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_40');                                                                                             
APROCKAPNEW(Y,AAA,'Methanation_45')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_45');                                                                                              
 APROCKAPNEW(Y,AAA,'Methanation_50')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanation_50');                                                                                             
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_20')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_20');                                                                                    
 APROCKAPNEW(Y,AAA,'Biogas_Upgrading_25')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_25');                                                                                   
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_30')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_30');                                                                                    
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_35')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_35');                                                                                    
 APROCKAPNEW(Y,AAA,'Biogas_Upgrading_40')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_40');                                                                                   
 APROCKAPNEW(Y,AAA,'Biogas_Upgrading_45')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_45');                                                                                   
APROCKAPNEW(Y,AAA,'Biogas_Upgrading_50')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Biogas_Upgrading_50');                                                                                    
$label NO_BIOGAS                                                                                                                                                                               
APROCKAPNEW(Y,AAA,'TG_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_20');                                                                                                                
APROCKAPNEW(Y,AAA,'TG_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_25');                                                                                                                
APROCKAPNEW(Y,AAA,'TG_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_30');                                                                                                                
APROCKAPNEW(Y,AAA,'TG_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_35');                                                                                                                
APROCKAPNEW(Y,AAA,'TG_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_40');                                                                                                                
APROCKAPNEW(Y,AAA,'TG_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_45');                                                                                                                
 APROCKAPNEW(Y,AAA,'TG_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','TG_50');                                                                                                               
                                                                                                                                                                                               
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_20');                                                                          
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_25');                                                                          
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_30');                                                                          
 APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_35');                                                                         
 APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_40');                                                                         
APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_45');                                                                          
 APROCKAPNEW(Y,AAA,'Methanol_synthesis_TG_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Methanol_synthesis_TG_50');                                                                         
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_20');                                                                              
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_25');                                                                              
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_30');                                                                              
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_35');                                                                              
APROCKAPNEW(Y,AAA,'EMethanol_synthesis_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_40');                                                                              
 APROCKAPNEW(Y,AAA,'EMethanol_synthesis_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_45');                                                                             
 APROCKAPNEW(Y,AAA,'EMethanol_synthesis_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_synthesis_50');                                                                             
APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_20');                                                                                  
 APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_25');                                                                                 
 APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_30');                                                                                 
 APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_35');                                                                                 
 APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_40');                                                                                 
 APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_45');                                                                                 
 APROCKAPNEW(Y,AAA,'EMethanol_Upgrade_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','EMethanol_Upgrade_50');                                                                                 
                                                                                                                                                                                               
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_20');                                                                                  
 APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_25');                                                                                 
 APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_30');                                                                                 
 APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_35');                                                                                 
 APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_40');                                                                                 
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_45');                                                                                  
APROCKAPNEW(Y,AAA,'Ammonia_Synthesis_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Ammonia_Synthesis_50');                                                                                  
                                                                                                                                                                                               
APROCKAPNEW(Y,AAA,'BioJet_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_20');                                                                                                        
APROCKAPNEW(Y,AAA,'BioJet_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_25');                                                                                                        
APROCKAPNEW(Y,AAA,'BioJet_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_30');                                                                                                        
APROCKAPNEW(Y,AAA,'BioJet_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_35');                                                                                                        
APROCKAPNEW(Y,AAA,'BioJet_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_40');                                                                                                        
APROCKAPNEW(Y,AAA,'BioJet_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_45');                                                                                                        
APROCKAPNEW(Y,AAA,'BioJet_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_50');                                                                                                        
 APROCKAPNEW(Y,AAA,'BioJet_H2_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_20');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_25');                                                                                                  
APROCKAPNEW(Y,AAA,'BioJet_H2_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_30');                                                                                                  
 APROCKAPNEW(Y,AAA,'BioJet_H2_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_35');                                                                                                 
APROCKAPNEW(Y,AAA,'BioJet_H2_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_40');                                                                                                  
 APROCKAPNEW(Y,AAA,'BioJet_H2_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_45');                                                                                                 
 APROCKAPNEW(Y,AAA,'BioJet_H2_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','BioJet_H2_50');                                                                                                 
APROCKAPNEW(Y,AAA,'E_FT_20')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_20');                                                                                                            
APROCKAPNEW(Y,AAA,'E_FT_25')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_25');                                                                                                            
APROCKAPNEW(Y,AAA,'E_FT_30')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_30');                                                                                                            
APROCKAPNEW(Y,AAA,'E_FT_35')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_35');                                                                                                            
 APROCKAPNEW(Y,AAA,'E_FT_40')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_40');                                                                                                           
APROCKAPNEW(Y,AAA,'E_FT_45')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_45');                                                                                                            
 APROCKAPNEW(Y,AAA,'E_FT_50')$BIGAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','E_FT_50');                                                                                                           
                                                                                                                                                                                               
                                                                                                                                                                                               
APROCKAPNEW(Y,AAA,'Untouched_Forest')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Untouched_Forest');                                                                                          
APROCKAPNEW(Y,AAA,'Wood_Production')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Wood_Production');                                                                                            
APROCKAPNEW(Y,AAA,'C_Rich_Soils_Extraction')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','C_Rich_Soils_Extraction');                                                                            
APROCKAPNEW(Y,AAA,'Wheat_Agriculture')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Wheat_Agriculture');                                                                                        
APROCKAPNEW(Y,AAA,'Barley_Agriculture')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Barley_Agriculture');                                                                                      
APROCKAPNEW(Y,AAA,'Oat_Agriculture')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Oat_Agriculture');                                                                                            
APROCKAPNEW(Y,AAA,'Rye_Agriculture')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','Rye_Agriculture');                                                                                            
APROCKAPNEW(Y,AAA,'New_Productive_Forest')$MUNAAAOPTIFLOW(AAA)=APROCKAPNEW(Y,'Aarhus','New_Productive_Forest');                                                                                
