SET PROCSOURCE(PROC) "Start PROC (no trace entering)"
/                                                    
CO2_Source_BIOGEN                                    
CO2_Source_DAC                                       
CO2_Source_FOSSIL                                    
DieselSource                                         
HydrogenSource_MWh                                   
KeroseneSource                                       
MDOSource                                            
Productive_Forest_Land_Gen                           
Agricultural_Land_Gen                                
Wood_Pellets_Gen                                     
                                                     
Manure_Gen                                           
/;                                                   
